<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Iwas.Business.csproj" />
    <ProjectReference Include="..\Model\Iwas.Model.csproj" />
  </ItemGroup>
</Project>
